### ISSUE TITLE
JSX not rendering

### ISSUE THREAD

**Issue by ujjwal-poudel** [realCoderPrashant/dev-portfolio#1]
I creating my main navigation components however while I run the application it's not rendered in the root. Please create a new branch while fixing.

**Comment by Nabin-me** [comment]
The underlying issue was in the main.jsx, it was simply an import issue which was returning an error of 
`ReactDOM.createRoot is not a function.` in the console

Secondly, the navigationItems were not rendering due to an export issue which I figured could be fixed by exporting without a default

**Comment by ujjwal-poudel** [comment]
Thank you for helping me out

**Comment by ujjwal-poudel** [comment]
Closed
